name: Deploy
on: 
  push:
    branches:    
        - main
        
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install sass
        uses: borales/actions-yarn@v4
        with:
          cmd: add -D sass
      - name: Run generate
        uses: borales/actions-yarn@v4
        with:
          cmd: generate
      - name : Deploy to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .output/public
          remote: /srv/config/portfolio/generated
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey :  ${{ secrets.SSH_KEY }}
    
      
    
       
