name: Deploy
on: 
  push:
    branches:    
        - main
        
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: .git/
      - name : Deploy repo to the server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /srv/config/portfolio/project
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey :  ${{ secrets.SSH_KEY }}
      - name : Run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/config/portfolio
            docker-compose up -d  --build 
    
      
    
       
